# Generated by Django 3.1.7 on 2022-05-17 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220517_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.servicearea'),
            preserve_default=False,
        ),
    ]
