# Generated by Django 3.2.4 on 2022-05-20 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220520_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scientist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the developer', max_length=250)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, help_text='Is the scientist active?')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organization')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='scientists',
            field=models.ManyToManyField(blank=True, to='app.Scientist'),
        ),
    ]
