# Generated by Django 3.2.4 on 2022-05-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220520_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='developers',
            field=models.ManyToManyField(blank=True, related_name='developers', to='app.Developer'),
        ),
    ]
