# Generated by Django 4.0.4 on 2022-06-01 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220520_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='incomplete_info',
            field=models.BooleanField(default=True, help_text='Application needs more information added?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='deployment_environment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.deploymentenvironment'),
        ),
        migrations.AlterField(
            model_name='application',
            name='icon',
            field=models.ImageField(blank=True, upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization that developed the application', on_delete=django.db.models.deletion.CASCADE, to='app.organization'),
        ),
        migrations.AlterField(
            model_name='application',
            name='primary_developer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.developer'),
        ),
        migrations.AlterField(
            model_name='application',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
