# Generated by Django 4.0.4 on 2022-06-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_developer_photo_alter_scientist_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the region', max_length=250)),
                ('organization', models.ManyToManyField(blank=True, to='app.organization')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='region',
            field=models.ManyToManyField(blank=True, to='app.region'),
        ),
    ]
