# Generated by Django 4.0.4 on 2022-06-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_region_application_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='display_priority',
            field=models.IntegerField(blank=True, default=10, help_text='Display priority (lower numbers shown at the top of the list)'),
        ),
    ]
