# Generated by Django 4.0.4 on 2022-06-29 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_application_display_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Date issue or milestone happened'),
        ),
    ]
