# Generated by Django 4.0.4 on 2022-06-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_dataset_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcomponent',
            name='applications',
            field=models.ManyToManyField(blank=True, to='app.application'),
        ),
    ]
