# Generated by Django 4.0.4 on 2022-12-27 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_developer_applications_scientist_applications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, help_text='Link location')),
                ('description', models.TextField(blank=True, help_text='Details for the link')),
                ('additional_description', models.TextField(blank=True, help_text='Further details for the link')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='related_links',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.link'),
        ),
    ]
