# Generated by Django 4.0.4 on 2023-01-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_application_related_links_link_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='applications',
            field=models.ManyToManyField(blank=True, to='app.application'),
        ),
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.CharField(blank=True, help_text='Link Description', max_length=250),
        ),
    ]
