# Generated by Django 4.0.4 on 2023-08-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_servicearea_applications_alter_link_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='primary_developer',
        ),
    ]
