# Generated by Django 4.2.1 on 2024-04-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0020_application_ast_pi_application_ast_round"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="accronym",
            field=models.CharField(
                blank=True, help_text="Region accronym", max_length=4
            ),
        ),
    ]
