# Generated by Django 4.2.1 on 2024-05-17 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0022_deploymentenvironment_applications_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="user",
            field=models.ForeignKey(
                default=7,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
