# Generated by Django 4.2.1 on 2024-05-20 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0024_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
