# Generated by Django 4.2.1 on 2024-05-20 15:35

from django.db import migrations


def create_approver_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    # Create the group
    approver_group, created = Group.objects.get_or_create(name='Approver')

    if created:
        permissions = Permission.objects.filter(
            codename__in=['view_user', 'change_user', 'view_group', 'change_group']
        )
        approver_group.permissions.add(*permissions)


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0025_delete_customuser'),  # Adjust this to be the last migration file
    ]

    operations = [
        migrations.RunPython(create_approver_group),
    ]