# Generated by Django 4.2.1 on 2024-05-29 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0028_generalfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="resolved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="application",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.application",
            ),
        ),
        migrations.AlterField(
            model_name="generalfeedback",
            name="resolved",
            field=models.BooleanField(default=False),
        ),
    ]
