# Generated by Django 4.2.1 on 2024-05-29 21:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0029_feedback_resolved_alter_feedback_application_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GeneralFeedback",
        ),
    ]
