# Generated by Django 4.2.1 on 2024-06-05 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0031_like"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Primary URL of the application",
                        max_length=255,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Application name", max_length=250),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description. Why is the app relevant for SERVIR?",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "serviceareas",
                    models.ManyToManyField(blank=True, to="app.servicearea"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=7,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ExternalApps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
